#!/bin/sh

# Copyright © 2016-2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -e -u

if [ $# -eq 0 ]
then
    printf 'Usage: %s IMAGE [OPTIONS...]\n' "${0##*/}" >&2
    exit 1
fi

image=$1
shift

if [ "$image" = tmp ]
then
    image=$(mktemp tmpqemu.XXXXXXXX)
    trap 'rm -f "$image"' EXIT
    cp -L --sparse=always base.qemu "$image"
elif [ ! -e "$image" ]
then
    cp -L --sparse=always base.qemu "$image"
fi

image_dir="$(dirname "$image")"
[ "$image_dir" = . ]
image_base="$(basename "$image" .qemu)"
session_name="vm-$(basename "$image" .qemu)"

cpu=host
smp=$(nproc)
mem=1G
vga=virtio
display=curses
disk_if=virtio
nic_model=virtio
rtc='base=utc'
ssh_port=
storage_type=virtio

if [ -f options ]
then
    . ./options
fi
if [ -f "${image_base}.options" ]
then
    . "./${image_base}.options"
fi

usernet=user
if [ -n "$ssh_port" ]
then
    usernet="$usernet,hostfwd=tcp:127.0.0.1:$ssh_port-:22"
fi
if [ -d storage/ ]
then
    if [ "$storage_type" = virtio ]
    then
        set -- -virtfs local,path=storage/,mount_tag=storage,security_model=mapped "$@"
    elif [ "$storage_type" = fat ]
    then
        set -- -drive file=fat:rw:storage/,index=1,format=raw "$@"
    else
        printf '%s: invalid storage_type: %s' "$0" "$storage_type"
    fi
fi

tmux new-session -s "$session_name" \
qemu-system-x86_64 \
    -drive "file=$image,index=0,if=$disk_if,media=disk,discard=unmap" \
    -nodefaults \
    -cpu "$cpu" \
    -smp "$smp" \
    -m "$mem" \
    -vga "$vga" \
    -display "$display" \
    -net 'nic,model='$nic_model -net "$usernet" \
    -rtc "$rtc" \
    -object rng-random,filename=/dev/urandom,id=rng0 \
    -device virtio-rng-pci,rng=rng0 \
    "$@"

# vim:ts=4 sts=4 sw=4 et
